name: miscelaneos
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_compass: ^0.7.0
  flutter_riverpod: ^2.3.7
  go_router: ^10.1.0
  google_fonts: ^5.1.0
  permission_handler: ^10.4.3
  sensors_plus: ^3.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/compass/
